### ISSUE TITLE
Bundler/Rails Auto Require

### ISSUE THREAD

**Issue by wied03** [cj/opal-webpack#15]
This along with #5 is the last thing I need to work to migrate to this.

If Bundler is running (e.g. the BUNDLE_BIN env variable is set), then:
* [x] implicitly 'set' OPAL_USE_BUNDLER to true. If OPAL_USE_BUNDLER has been set to false explicitly, then don't override that.
* [x] Fire up Ruby
* [x] If RAILS_ENV is set, call `require File.expand_path('config/environment')`
* [x] If it's not set, call `Bundler.require`
* [x] all tests pass

Add a new config option called mriRequires. If that option is set, it will:
* [x] Fire up Ruby
* [x] Issue a require on each option

Then it will print out the load paths all of those Gems (and code) have added and add those to the OPAL_LOAD_PATH in this webpack loader. That way you don't have to do any extra work IF you're in a Ruby project and you want to do that.

**Comment by cj** [comment]
I'm not a fan of adding rails specific stuff, but I guess that's because I don't use it. I see why you would though as it's the most used framework. what about allowing you to specify the require, that way it would work with any other framework too that has something like File.expand_path('config/environment')

I know some people don't use bundler, so giving the 3rd option to pass your own require would cover 100% of the cases
